# postrsql 디비 유저 다른 user 사용할때 슈퍼유저에서 아래 3가지 실행하고 접속하기
# 
# example :  Mastr/Salve 

# 1. docker 컨테이너 내부에서 접속 (postrsql)
# -- 새 유저 생성
# CREATE USER hellopsql WITH PASSWORD '';

# -- 특정 데이터베이스에 모든 권한 부여
# GRANT ALL PRIVILEGES ON DATABASE your_database TO hellopsql;

# -- 슈퍼유저 권한 부여
# ALTER USER hellopsql WITH SUPERUSER;


services:
  web:
    build: .
    container_name: django_app

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - ./.env
    
    command: sh -c "python manage.py makemigrations && python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db



  db:
    image: postgres:16
    
    restart : always
    
    env_file:
      - ./.env

    ports:
      - 5433:5432

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/



volumes:
  postgres_data:




