services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"

    env_file:
      - ./.env
      
    command: sh -c "python manage.py makemigrations && python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:16
    
    restart : always
    
    env_file:
      - ./.env

    ports:
      - 5433:5432
      
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:


